### ISSUE TITLE
v2.2.6 is breaking builds

### ISSUE THREAD

**Issue by nhammond101** [nrwl/nx-set-shas#59]
Issue: 
CI Builds are failing on the `Setup nx` step

Expected:
Builds to continue past the step with the correct SHAs set for `affected:*` commands

Actual:
```
Run nrwl/nx-set-shas@v2
  with:
    main-branch-name: main
    set-environment-variables-for-job: true
    error-on-no-successful-workflow: false
    last-successful-event: push
    working-directory: .
  env:
    ...
Run node $GITHUB_ACTION_PATH/dist/index.js
  node $GITHUB_ACTION_PATH/dist/index.js
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    ...
Warning: 

Warning: WARNING: Working directory '' doesn't exist.

fatal: Not a valid object name origin/
(node:1[7](https://github.com/Unity-Technologies/sol-naemo-world-monorepo/runs/8154717695?check_suite_focus=true#step:8:7)12) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/errors:[8](https://github.com/Unity-Technologies/sol-naemo-world-monorepo/runs/8154717695?check_suite_focus=true#step:8:8)56
  const err = new Error(message);
              ^

Error: Command failed: git merge-base origin/"" HEAD
fatal: Not a valid object name origin/

    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:[9](https://github.com/Unity-Technologies/sol-naemo-world-monorepo/runs/8154717695?check_suite_focus=true#step:8:9)12:15)
    at /home/runner/work/_actions/nrwl/nx-set-shas/v2/dist/index.js:62822:16
    at /home/runner/work/_actions/nrwl/nx-set-shas/v2/dist/index.js:62855:3
    at /home/runner/work/_actions/nrwl/nx-set-shas/v2/dist/index.js:62930:3
    at Object.<anonymous> (/home/runner/work/_actions/nrwl/nx-set-shas/v2/dist/index.js:62933:12)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:[10](https://github.com/Unity-Technologies/sol-naemo-world-monorepo/runs/8154717695?check_suite_focus=true#step:8:10))
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  status: [12](https://github.com/Unity-Technologies/sol-naemo-world-monorepo/runs/8154717695?check_suite_focus=true#step:8:12)8,
  signal: null,
  output: [ null, '', 'fatal: Not a valid object name origin/\n' ],
  pid: [17](https://github.com/Unity-Technologies/sol-naemo-world-monorepo/runs/8154717695?check_suite_focus=true#step:8:17)[21](https://github.com/Unity-Technologies/sol-naemo-world-monorepo/runs/8154717695?check_suite_focus=true#step:8:22),
  stdout: '',
  stderr: 'fatal: Not a valid object name origin/\n'
}
Error: Process completed with exit code 1.
```

Workaround:
Pin the step to v2.2.5
```yaml
- name: Setup nx
  uses: nrwl/nx-set-shas@v2.2.5
```

Further information:
The checkout step is pulling the full repo
```yaml
- uses: actions/checkout@v3
  with:
    fetch-depth: 0
```

**Comment by breningham** [comment]
the issue i think is 
https://github.com/nrwl/nx-set-shas/compare/v2.2.5...v2.2.6#diff-170a08b1978a85acbe69409c7515842e159c8872f2c10014aceb82f1716e8d81R29

**Comment by pgte** [comment]
Happening to me too

**Comment by flaviouk** [comment]
Same with us, is there a way to fix a github action version to a commit maybe?

**Comment by tamascsaba** [comment]
I think it will be related lot of projects.

**Comment by flaviouk** [comment]
Same with us, reverting to the workaround solution for now

**Comment by zbaibolov** [comment]
same situation

**Comment by tamascsaba** [comment]
Here is a good meme to tide you over until the guys resolve this issue :) 

![image](https://user-images.githubusercontent.com/3479963/188137668-70fb2f77-c679-4f5e-a46a-00bdf2a09db0.png)

**Comment by rmlevangelio** [comment]
😓

**Comment by PodStuart** [comment]
Don't think workaround is viable if using the nx-cloud-main.yml workflow.

**Comment by JamesHenry** [comment]
Hi Folks, deja vu from yesterday, but I saw these notifications and have again reverted the relevant PR and cut a later patch - `2.2.7`, so things should hopefully be working again now

**Comment by mkurczewski** [comment]
![image](https://user-images.githubusercontent.com/15341913/188140555-ea81148e-a87f-4b49-a1cd-8136ac5a0b6f.png)

**Comment by ricardodantas** [comment]
Same here

**Comment by LayZeeDK** [comment]
@JamesHenry
I had already submitted a bugfix patch. I will rework it to include the security improvement at some other time then.

**Comment by tamascsaba** [comment]
Thank you very much man, we greatly appreciate your quick fix 👍
